name: Go tests

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  test-webassembly:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go: ["1.24", "1.25"]
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: 0
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: |
          go test ./... -coverprofile=coverage.out -covermode=atomic -v
      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.go == '1.25'
        uses: codecov/codecov-action@v4
        with:
          files: coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Test build
        run: |
          go build main.go

  test-alpine:
    strategy:
      fail-fast: false
      matrix:
        go: [ "1.24", "1.25" ]
    runs-on: ubuntu-latest
    container:
      image: alpine:3.22
      env:
        CGO_ENABLED: 1
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Set up libjpeg-turbo
        run: |
          apk add --no-cache pkgconf libturbojpeg libjpeg-turbo-dev
      - name: Set up musl
        run: |
          apk add --no-cache musl build-base perl git musl-dev
      - name: Run tests
        run: |
          go test ./... -tags libtiff_use_turbojpeg -v
      - name: Test build
        run: |
          go build -tags libtiff_use_turbojpeg main.go

  test-cgo-linux:
    strategy:
      fail-fast: false
      matrix:
        go: [ "1.24", "1.25" ]
    env:
      CGO_ENABLED: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Set up libjpeg-turbo
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libturbojpeg libturbojpeg-dev

      - name: Test Linux
        run: |
          go test ./... -tags libtiff_use_turbojpeg -v

      - name: Build
        run: |
          go build -tags libtiff_use_turbojpeg main.go